name: Docker CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Eslint
  #       run:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.1.6
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.2.0
      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1.1.3
      - name: Run hadolint with reviewdog
        uses: reviewdog/action-hadolint@v1.0.4

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Log into Docker Hub
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image
        run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/data homeassistant/amd64-builder --all -t filiikot --test
